// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/adoptme': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/adoptme').default>>>>
    }
    '/api/chat-InitialMessage': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat-InitialMessage').default>>>>
    }
    '/api/chat-NewMessage': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat-NewMessage').default>>>>
    }
    '/api/chat-sendmsg': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat-sendmsg').default>>>>
    }
    '/api/gag-live-stock': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/gag-live-stock').default>>>>
    }
    '/api/gag': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/gag').default>>>>
    }
    '/api/values-restaurant': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/values-restaurant').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}