// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/9/2025, 10:07:07 pm
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/Harsh Choudhary/Desktop/silverfox-new/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Harsh Choudhary/Desktop/silverfox-new/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Harsh Choudhary/Desktop/silverfox-new/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Harsh Choudhary/Desktop/silverfox-new/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Harsh Choudhary/Desktop/silverfox-new/plugins/**/*.{js,ts,mjs}","C:/Users/Harsh Choudhary/Desktop/silverfox-new/composables/**/*.{js,ts,mjs}","C:/Users/Harsh Choudhary/Desktop/silverfox-new/utils/**/*.{js,ts,mjs}","C:/Users/Harsh Choudhary/Desktop/silverfox-new/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Harsh Choudhary/Desktop/silverfox-new/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Harsh Choudhary/Desktop/silverfox-new/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Harsh Choudhary/Desktop/silverfox-new/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;